# Generated by Django 3.2.16 on 2022-11-30 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='close_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 30, 8, 48, 14, 749256), verbose_name='date closed'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 30, 7, 48, 14, 749235), verbose_name='date published'),
        ),
    ]
